services:
  postgres:
    image: postgres:16.3-alpine
    container_name: l3_2_postgres
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
      - POSTGRES_DB=app
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-net

  app:
    build:
      context: ..
      dockerfile: L3_2/Dockerfile
    container_name: l3_2_app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DSN=postgres://app:app@postgres:5432/app?sslmode=disable
    ports:
      - "8080:8080"
    networks:
      - app-net
volumes:
  pg_data:

networks:
  app-net:
